# Generated by Django 5.2.6 on 2025-10-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('conference_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('theme', models.CharField(choices=[('AI', 'Computer Science & Artificial Intelligence'), ('SE', 'Science & Engineering'), ('SSE', 'Social Sciences & Education'), ('INT', 'Interdisciplinary Themes')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
