# Generated by Django 5.2.6 on 2025-10-03 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='This field should contain only alphabetic characters.', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='This field should contain only alphabetic characters.', regex='^[a-zA-Z\\s]+$')]),
        ),
    ]
