# Generated by Django 5.2.6 on 2025-10-03 14:44

import userApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[userApp.models.validateEmail]),
        ),
    ]
